version: '3'
services:
  demo:
    build: .
    container_name: demo
    volumes:
      - ./bin:/app/bin
      - ./config:/app/config
      - ./public:/app/public
      - ./src:/app/src
      - ./src-js/src:/app/src-js/src
      - ./src-js/package.json:/app/src-js/package.json
      - ./src-js/tsconfig.json:/app/src-js/tsconfig.json
      - ./src-js/webpack.config.js:/app/src-js/webpack.config.js
      - ./src-js/yarn.lock:/app/src-js/yarn.lock
      - ./tests:/app/tests
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./symfony.lock:/app/symfony.lock
      - ./phpunit.xml.dist:/app/phpunit.xml.dist
      - ./infection.json.dist:/app/infection.json.dist
      - ./phpcs.xml.dist:/app/phpcs.xml.dist
      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
