# demo
services:
  _defaults:
    autowire: true
    autoconfigure: true

    bind:
      $env: '%kernel.environment%'

  App\Common\Listener\:
    resource: '../Listener/'

  App\Common\Service\:
    resource: '../Service/'

  App\Common\Command\:
    resource: '../Command'
    tags: ['console.command']
