# demo
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Exercises\IO\Controller\:
    resource: '../IO/Controller/'
    tags: ['controller.service_arguments']

twig:
  default_path: '%kernel.project_dir%/templates'
  paths: [ '%kernel.project_dir%/src/Exercises/_templates' ]
