# demo
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

    bind:
      $theySaidSoApiKey: 'xxxxx'


  App\Demo\IO\Controller\:
    resource: '../IO/Controller/'
    tags: ['controller.service_arguments']

  App\Demo\IO\Command\:
    resource: '../IO/Command'
    tags: ['console.command']

  App\Demo\Application\Query\Handler\:
    resource: '../Application/Query/Handler'
    tags: [{name: messenger.message_handler }]

  App\Demo\Infrastructure\:
    resource: '../Infrastructure/'

  App\Demo\Infrastructure\JsonShoutReadModel:
    arguments: [ '%kernel.project_dir%/%env(QUOTES_JSON_FILE)%']

  App\Demo\Infrastructure\ExceptionListener:
    arguments: [ '%kernel.environment%' ]
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Demo\Application\Service\Bus: '@App\Demo\Infrastructure\SymfonyBus'
  App\Demo\Application\Service\Cache: '@App\Demo\Infrastructure\FilesystemCache'

  App\Demo\Application\Service\ShoutReadModel: '@App\Demo\Infrastructure\JsonShoutReadModel'
